module M3U8
  module Protocol
    # Basic Tags
    EXTM3U = "#EXTM3U"
    EXT_X_VERSION = "#EXT-X-VERSION"

    # media segment tags
    EXTINF = "#EXTINF"
    EXT_X_BYTERANGE = "#EXT-X-BYTERANGE"
    EXT_X_DISCONTINUITY = "#EXT-X-DISCONTINUITY"
    EXT_X_KEY = "#EXT-X-KEY"
    EXT_X_MAP = "#EXT-X-MAP"
    EXT_X_PROGRAM_DATE_TIME = "#EXT-X-PROGRAM-DATE-TIME"
    EXT_X_DATERANGE = "#EXT-X-DATERANGE"

    # Media Playlist Tags
    EXT_X_TARGETDURATION = "#EXT-X-TARGETDURATION"
    EXT_X_MEDIA_SEQUENCE = "#EXT-X-MEDIA-SEQUENCE"
    EXT_X_DISCONTINUITY_SEQUENCE = "#EXT-X-DISCONTINUITY-SEQUENCE"
    EXT_X_ENDLIST = "#EXT-X-ENDLIST"
    EXT_X_PLAYLIST_TYPE = "#EXT-X-PLAYLIST-TYPE"
    EXT_X_I_FRAMES_ONLY = "#EXT-X-I-FRAMES-ONLY"
    EXT_X_ALLOW_CACHE = "#EXT-X-ALLOW-CACHE"

    # Master Playlist Tags
    EXT_X_MEDIA = "#EXT-X-MEDIA"
    EXT_X_STREAM_INF = "#EXT-X-STREAM-INF"
    EXT_X_I_FRAME_STREAM_INF = "#EXT-X-I-FRAME-STREAM-INF"
    EXT_X_SESSION_DATA = "#EXT-X-SESSION-DATA"
    EXT_X_SESSION_KEY = "#EXT-X-SESSION-KEY"

    # Media or Master Playlist Tags
    EXT_X_INDEPENDENT_SEGMENTS = "#EXT-X-INDEPENDENT-SEGMENTS"
    EXT_X_START = "#EXT-X-START"

    # Experimental Tags
    EXT_X_CUE_OUT = "#EXT-X-CUE-OUT"
    EXT_X_CUE_OUT_CONT = "#EXT-X-CUE-OUT-CONT"
    EXT_X_CUE_IN = "#EXT-X-CUE-IN"
    EXT_X_CUE_SPAN = "#EXT-X-CUE-SPAN"
    EXT_OATCLS_SCTE35 = "#EXT-OATCLS-SCTE35"
  end
end

